name: Daily Automated Commit

on:
  # Runs daily at 02:30 AM UTC
  schedule:
    - cron: '30 2 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  daily_update:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full history

      # Ensure we are up-to-date with main
      - name: Pull latest changes from remote
        run: |
          git config --global user.name "DevSync Automation Bot"
          git config --global user.email "automation@devsync.com"
          git pull --rebase origin main || true

      # ✅ Step required in name
      - name: 24f3003529@ds.study.iitm.ac.in
        run: echo "Step with required name executed successfully."

      # Create or update the log file
      - name: Generate daily update file
        run: echo "Daily automated run at $(date)" >> daily_update_log.txt

      # Commit and push
      - name: Auto Commit daily_update_log.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated Daily Update: $(date +'%Y-%m-%d')"
          file_pattern: daily_update_log.txt
          commit_user_name: "DevSync Automation Bot"
          commit_user_email: "automation@devsync.com"
          push_options: '--force'
